### ISSUE TITLE
Timeline inconsistent

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#165]
# Problem

The timeline is either not visible or takes very little space or too much. Maybe possible to let it cover the given space even if it is a short interval or a long interval? 

Browser: Safari, Chrome

## Analysis 1: Timeline not visible
Spread link: https://view.spreadviz.org/?output=94d05c76-0585-43f9-99d8-9e13973ebba0/f97a0171-7836-4f7c-8dc0-d4eeef938d21.json&maps=DK,FR,RU,BE,UK,PT,SE
<img width="1974" alt="image" src="https://user-images.githubusercontent.com/29096492/151148097-867ab364-c7e6-4c11-a158-c27f0dd86951.png">
Files: [SARS-CoV-2discrete.zip](https://github.com/fbielejec/spread/files/7941118/SARS-CoV-2discrete.zip)

## Analysis 2: Timeline takes up very little space
Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/f755822e-7743-4e97-ad71-d7f3303bae88.json&maps=GH,BF,GN,SL,TG
<img width="1974" alt="image" src="https://user-images.githubusercontent.com/29096492/151148132-e664bc68-15ba-45c7-85c6-5103ebaf340c.png">
Files: [chiefdom_ebola.zip](https://github.com/fbielejec/spread/files/7941121/chiefdom_ebola.zip)

## Analysis 3: Timeline takes more space than previous but still does not cover up the whole area
Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/b6cce491-3fc3-4725-9fd8-a0e56b5afa19.json&maps=RU,MX,US,BS,CA
<img width="1974" alt="image" src="https://user-images.githubusercontent.com/29096492/151148166-2f7f28a6-c141-4dc4-bb6c-c28ad948e849.png">
Files: [wnv.zip](https://github.com/fbielejec/spread/files/7941125/wnv.zip)

## Analysis 4: Timeline goes outside the given box
Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/9fe1c695-e1ff-441d-9dc0-9c23441c873b.json&maps=GH,NG,CM,BF,GN,SL,ML
<img width="1974" alt="image" src="https://user-images.githubusercontent.com/29096492/151148275-26c5a353-61d5-45e3-b68a-f2bdc347417b.png">

**Comment by fbielejec** [comment]
@jpmonettas could we just make it occuppy the entire availiable space?

**Comment by jpmonettas** [comment]
This PR (https://github.com/fbielejec/spread/pull/188) redesigns the timeline controls at the bottom. It will use the entire length to draw the timeline.

Big timelines will show like :
![1645207872](https://user-images.githubusercontent.com/786299/154739943-66c81ee6-c7f6-49e1-b014-54f413763341.png)

While very short timelines (under a year) like : 
![1645207934](https://user-images.githubusercontent.com/786299/154739973-886ddac5-f73f-43e9-a4a7-01d8bc17bf4b.png)

Since we are only labeling year marks, that last case when everything happens under a year will show unlabeled
