### ISSUE TITLE
maps do not cross dateline

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#166]
# Problem

Maps end at the dateline leading to blank space when scrolling left or right (as shown in the movie below).
https://user-images.githubusercontent.com/29096492/151525313-45a37643-7c94-413a-ac1d-bf0fc3725d74.mov

### Would it be possible to have a map like google does? 
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/29096492/151523481-97cbc118-b559-450d-8204-660179beb49a.png">

### Similar to issues raised by SpreaD3 users:
- https://github.com/phylogeography/SpreaD3/issues/40
- https://github.com/phylogeography/SpreaD3/issues/31 
![around_the_world_map](https://user-images.githubusercontent.com/29096492/151524357-193dbe5e-22f9-49d3-b1df-96374ae60629.png)

**Comment by jpmonettas** [comment]
I'm not 100% sure what this is about. I see that on google maps you have this infinite panning and it wraps around. I'm not sure how that should work for animations like transitions, but pretty sure we can NOT implement it because of how we are drawing maps and animation objects using svg instead of a canvas.

**Comment by amymariecampbell** [comment]
I don't think infinite panning is necessary, but if the shorter/more likely journey is across the pacific (ie leaving the svg on the right and then reappearing on the left), it would be good if it could show that direction rather than a longer/ less likely route restricted by a 2D dateline-defined map
