### ISSUE TITLE
Problem visualising in Safari

### ISSUE THREAD

**Issue by GuyBaele** [phylogeography/spread#181]
The following visualisation works fine in Google Chrome and Firefox (see screenshot attached):
https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/dcfb953a-9a35-4bb6-bc15-2643036b57b0.json&maps=CN,KP,BD,RU,NP,BT,MN

However, in Safari, neither the map nor animations are visible (confirmed by Marc and myself; see screenshot attached).

<img width="2672" alt="Screenshot 2022-02-16 at 16 10 13" src="https://user-images.githubusercontent.com/1092968/154294775-5ed02fd8-853e-4a1a-b526-782ef5c6bf87.png">

<img width="2672" alt="Screenshot 2022-02-16 at 16 10 18" src="https://user-images.githubusercontent.com/1092968/154294739-9002e848-248c-4ae4-ba1f-b7f6abbcd7f2.png">

**Comment by fbielejec** [comment]
```
Error: <path> attribute d: Expected number, "…3.7633 66.621 Q NaN NaN 293.7633…".
```

**Comment by jpmonettas** [comment]
I don't have any Safari device to test, but assuming adding a svg path with NaN attributes breaks it (firefox and chrome probably skip them) this PR (https://github.com/fbielejec/spread/pull/183) filters out all transitions of length zero which are the cause of that behavior.
Maybe we should fix that sooner in the pipeline (analysis code) since it doesn't make sense to generate output like that to start with.
This issue will be closed once the PR gets merged but please reopen if Safari keeps breaking after the fix.
